### ISSUE TITLE
Link parse failure in org file

### ISSUE THREAD

**Issue by kimo-k** [200ok-ch/org-parser#30]
file: test.org:
```
[[https://example.com][link]]
```

output of `lein run test.org`:
```
[[:content "[[https://example.com][link]]\n"]]
```

expected output:
```
[[:link-format [:link [:link-ext [:link-ext-other
	                                      [:link-url-scheme "https"]
	                                      [:link-url-rest "//example.com"]]]]
	      [:link-description "link"]]]
```

Looking through the grammar but I don't see any obvious reason this fails. Any ideas?

Thanks for this nice & healthy library! Org-mode is underrated.

**Comment by schoettl** [comment]
Thank you for the report! The fix for this is pending in PR #27 

I hope we can soon finish and merge it.

**Comment by kimo-k** [comment]
Thanks for the quick update. I'm on your PR now, works great.

**Comment by schoettl** [comment]
Nice to hear!

Please be aware, that the parse tree structure will change every now and then – as long we don't have a stable release. That's unavoidable when refactoring or changing the EBNF.
