### ISSUE TITLE
cannot include org-parser as a dependency in a cljs node project using shadow-cljs

### ISSUE THREAD

**Issue by jobez** [200ok-ch/org-parser#61]
**Describe the bug**
I included org-parser as a dependency and built a cljs project for node using shadow cljs. Upon running the script, node errors out with the following output

```
Error: ENOENT: no such file or directory, open 'resources/org.ebnf'
    at Object.openSync (node:fs:582:3)
    at Object.instaparse.core/parser [as readFileSync] (node:fs:450:35)
    at /Users/jmsb/exps/clj/subsums/.shadow-cljs/builds/app/dev/out/cljs-runtime/org_parser/parser.cljs:8:1
    at global.SHADOW_IMPORT (/Users/jmsb/exps/clj/subsums/target/org.js:64:44)
    at /Users/jmsb/exps/clj/subsums/target/org.js:1718:1
    at Object.<anonymous> (/Users/jmsb/exps/clj/subsums/target/org.js:1725:3)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
```
**To Reproduce**
add org-parser as a dependency in a shadow-cljs project, 
include `org-parser.core` 
and call `read-str` from main

**Expected behavior**
Perhaps I am mistaken, but it would be nice to be able to include the project as a dependency in other cljs projects

**Screenshots**

**Additional context**

**Comment by schoettl** [comment]
Thanks for reporting! I'm not at all familiar with clojure packaging but it looks like our resources folder is not packaged along with other source and test files. The [project.clj](https://github.com/200ok-ch/org-parser/blob/master/project.clj) does not mention "resources". @munen @branch14 maybe it only has to be added to the `source-paths` array?

**Comment by wildwestrom** [comment]
Same exact problem on my project :(

**Comment by branch14** [comment]
This line will only work when the working directory is the root of org-parser itself. :(

https://github.com/200ok-ch/org-parser/blob/master/src/org_parser/parser.cljs#L8

This makes it unusable when "packaged".

To resolve this we've to find a way to specify the path to the ebnf file relative to the cljs
which is reading it.

As a hacky workaround you can just copy `resources/org.ebnf` to the resources directory of you project. That should work.

**Comment by jobez** [comment]
assuming that you can initialize the parser from a string, another option is to use a macro in the cljs compilation process to inline the ebnf file in the cljs file at compile time. shadow-cljs has an example of such a macro https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/resource.clj

**Comment by munen** [comment]
I have created a minimal demo application to showcase how org-parser does not work within a shadow-cljs application. The demo app is also minimally documented to get other developers started more easily: https://github.com/200ok-ch/org-parser-shadow_cljs-demo

**Comment by munen** [comment]
Closing thanks to https://github.com/200ok-ch/org-parser/pull/63

Thank you for opening the issue and creating instructions on how to test @jobez :pray:

**Comment by munen** [comment]
org-parser 0.1.27 should work from within shadow-cljs.
