### ISSUE TITLE
latest release to clojars

### ISSUE THREAD

**Issue by skovuri41** [200ok-ch/org-parser#65]
when is the next release planned to clojars? seems the latest version there does not support TODO and Priority parsing? thanks.

**Comment by munen** [comment]
Hi there, thanks for checking out org-parser!

We have automated releases to Clojars. 0.1.27 is the latest release. And of course it supports Org mode basics like TODO and priority parsing. Relevant test for priority parsing is here: https://github.com/200ok-ch/org-parser/blob/master/test/org_parser/parser_test.cljc#L79, for TODO is here: https://github.com/200ok-ch/org-parser/blob/master/test/org_parser/parser_test.cljc#L91

Hence, please reformulate your question.

**Comment by skovuri41** [comment]
thanks for response. i  confirm ver 0.1.27 is working as expected for TODO and priority. I had to clear cache files in my workspace after you confirmed and check again. I am excited about possibilities now for my personal projects , i use org extensively. thanks

**Comment by munen** [comment]
Good luck, have fun!
