### ISSUE TITLE
Question on this project's goal

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/org-parser#8]
Quoting @munen from https://github.com/200ok-ch/org-parser/pull/5#issuecomment-583695244

> The applications using the parser will also use the produced data structures. They might transform them into something else if they need to.

I read the quoted thread one time, but I'm not yet sure, if I fully understand this projects goal:

1. As an end-result, do we want to provide the plain parse tree, returned by the [instaparse's](http://xahlee.info/clojure/clojure_instaparse.html) `parse` function?

2. Or do we want to provide **both**, the plain parse tree and a higher-level data structure, returned by instaparse's `transform` function?

Please see [this example](https://github.com/200ok-ch/org-parser/pull/7#issuecomment-615449934) for the difference of 1 and 2.

Number 2. probably makes sense because otherwise organice and any other app using the parser have to do basically the same transformations.

Note: that instaparse is a very basic (do one thing well) parser compared to e.g. pegjs, where the EBNF grammar can be combined with JS code to generates higher-level data structures directly.

**Comment by munen** [comment]
Good question!

I agree that it makes sense to transform the parse tree to something that’s more reasonable to consume for a client application! It also makes sense to think of documentation for that structure, because it will act as an implicit API between client and org-parser.

NB: Clojure is great for such data transformations. Apart from the built in tooling and the linked transform function, there’s many good tools like:
- https://github.com/noprompt/meander
- https://github.com/redplanetlabs/specter

**Comment by rollacaster** [comment]
Hi!

To add one more option I tried to solve this with [clojure.zip](https://clojure.github.io/clojure/clojure.zip-api.html) and [it  worked quite well](https://github.com/rollacaster/org-parser-tree/blob/main/src/tech/thomas_sojka/org_parser_tree/core.clj) (at least until now but only minimal features have been implemented yet)

**Comment by munen** [comment]
@rollacaster Agreed, clojure.zip is a good option, too!

In https://github.com/200ok-ch/org-parser/blob/master/src/org_parser/transform.cljc, we've opted to just to with the simplest option at this time: `map` and `reduce`(;

@schoettl I'd say we can close this issue. I'll try to be a bit more explicit in the readme in the next commit. If there's ambiguity still, just re-open and make a suggestion on the wording^^
